myName = input("What is your name?:  ")
myAge = input("How old are you?:  ")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit?:  ")
print("Of course you do!")
print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that replit is")
print(replit)
print()
print()
myFavouriteFood = input("what's your favorite food?: ")
myaFavouriteMusic = input("What's your favorite music?: ")
myLocation = input("Where do you live?: ")
print()
print("You are")
print(myName)
print("You're probably hungry for")
print(myFavouriteFood)
print("and you're definitely getting your groove on to")
print(myaFavouriteMusic)
print("living in the amazing")
print(myLocation)
