myName = input("What is your name?:  ")
myAge = input("How old are you?:  ")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit?:  ")
print("Of course you do!")
print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that replit is")
print(replit)